---
test_name: 01-Enable PKI secret engine

stages:
  - name: Mount end at pki endpoint
    request:
      url: "{tavern.env_vars.VAULT_ADDR}/v1/sys/mounts/pki"
      method: POST
      headers:
        X-Vault-Token: "{tavern.env_vars.VAULT_TOKEN}"
      json:
        type: pki
    response:
      status_code: 404

---
test_name: 02-Tune PKI secret engine
stages:
  - name: 02-Tune PKI secret engine
    request:
      url: "{tavern.env_vars.VAULT_ADDR}/v1/sys/mounts/pki/tune"
      method: POST
      headers:
        X-Vault-Token: "{tavern.env_vars.VAULT_TOKEN}"
      json:
        max_lease_ttl: "87600h"
    response:
      status_code: 204
---
test_name: 03-Generate the CA cert
stages:
  - name: 03-Generate the CA cert
    request:
      url: "{tavern.env_vars.VAULT_ADDR}/v1/pki/root/generate/internal"
      method: POST
      headers:
        X-Vault-Token: "{tavern.env_vars.VAULT_TOKEN}"
      json:
        common_name: "example.com"
        ttl: "87600h"
    response:
      status_code: 200
      save:
        $ext:
          function: myutils:save_response
          extra_kwargs:
            filenane: ca.json
---
test_name: 04-Configure the CA and CRL URLs
stages:
  - name: 04-Configure the CA and CRL URLs
    request:
      url: "{tavern.env_vars.VAULT_ADDR}/v1/pki/config/urls"
      method: POST
      headers:
        X-Vault-Token: "{tavern.env_vars.VAULT_TOKEN}"
      json:
        issuing_certificates: "http://127.0.0.1:8200/v1/pki/ca"
        crl_distribution_points: "http://127.0.0.1:8200/v1/pki/crl"
    response:
      status_code: 204

---
test_name: 05-Generate Intermediate CA
stages:
  - name: 05-Generate Intermediate CA
    request:
      url: "{tavern.env_vars.VAULT_ADDR}/v1/sys/mounts/pki_int"
      method: POST
      headers:
        X-Vault-Token: "{tavern.env_vars.VAULT_TOKEN}"
      json:
        type: "pki"
    response:
      status_code: 204

---
test_name: 06-Tune PKI secret engine for Interneduate CA
stages:
  - name: 06-Tune PKI secret engine for Interneduate CA
    request:
      url: "{tavern.env_vars.VAULT_ADDR}/v1/sys/mounts/pki_int/tune"
      method: POST
      headers:
        X-Vault-Token: "{tavern.env_vars.VAULT_TOKEN}"
      json:
        max_lease_ttl: "87600h"
    response:
      status_code: 204
---
test_name: 07-Generate the Intermediate CA csr and sing it
stages:
  - name: 07-Generate the Intermediate CA csr
    request:
      url: "{tavern.env_vars.VAULT_ADDR}/v1/pki_int/intermediate/generate/internal"
      method: POST
      headers:
        X-Vault-Token: "{tavern.env_vars.VAULT_TOKEN}"
      json:
        common_name: "example.com Intermediate Authority"
    response:
      status_code: 200
      save:
        $ext:
          function: myutils:save_response
          extra_kwargs:
            filenane: intermediate_ca.json
        body:
          csr: data.csr
  - name: 08-Sign Intermediate CA
    request:
      url: "{tavern.env_vars.VAULT_ADDR}/v1/pki/root/sign-intermediate"
      method: POST
      headers:
        X-Vault-Token: "{tavern.env_vars.VAULT_TOKEN}"
      json:
        csr: "{csr}"
        format: pem_bundle
        ttl: 43800h
    response:
      status_code: 200
      save:
        $ext:
          function: myutils:save_response
          extra_kwargs:
            filenane: signed_intermediate_ca.json
        body:
          inter_crt: data.certificate

  - name: 09-Import Intermediate CA into pki_int
    request:
      url: "{tavern.env_vars.VAULT_ADDR}/v1/pki_int/intermediate/set-signed"
      method: POST
      headers:
        X-Vault-Token: "{tavern.env_vars.VAULT_TOKEN}"
      json:
        certificate: "{inter_crt}"
    response:
      status_code: 204    