---
test_name: 01-Enable PKI secret engine

stages:
  - name: Mount end at pki endpoint
    request:
      url: "{tavern.env_vars.VAULT_ADDR}/v1/sys/mounts/pki"
      method: POST
      headers:
        X-Vault-Token: "{tavern.env_vars.VAULT_TOKEN}"
      json:
        type: pki
    response:
      status_code: 404

---
test_name: 02-Tune PKI secret engine
stages:
  - name: Tune
    request:
      url: "{tavern.env_vars.VAULT_ADDR}/v1/sys/mounts/pki/tune"
      method: POST
      headers:
        X-Vault-Token: "{tavern.env_vars.VAULT_TOKEN}"
      json:
        max_lease_ttl: "87600h"
    response:
      status_code: 204
---
test_name: 03-Generate the CA cert
stages:
  - name: 03-Generate the CA cert
    request:
      url: "{tavern.env_vars.VAULT_ADDR}/v1/pki/root/generate/internal"
      method: POST
      headers:
        X-Vault-Token: "{tavern.env_vars.VAULT_TOKEN}"
      json:
        common_name: "example.com"
        ttl: "87600h"
    response:
      status_code: 200
      save:
        $ext:
          function: myutils:save_response
          extra_kwargs:
            filenane: ca.crt
        body:
          certificate: data
          
